### PR TITLE
fixed syntax error in cookiecutter.json

### PR DESCRIPTION
**Pull request by BadgerOps**
Noticed there was a missing comma in this file, thanks for a good base template!

### CODE REVIEW

**Comment by pdpinch** [comment]
@blarghmatey can you or @bdero review this?

**Comment by blarghmatey** [comment]
@BadgerOps Thanks for the fix! I'm glad you like the template. If you don't mind my asking, how did you find it?

**Comment by BadgerOps** [comment]
My google-fu is strong ;) - I was searching for a base template that included some testing stubs, as I'm looking to tinker around with pyobjects and testing before pushing code up.

**Comment by blarghmatey** [comment]
You might be interested in checking out the work I did to create a [TestInfra state module](https://github.com/mitodl/salt-extensions/blob/master/extensions/_states/testinframod.py). It is currently not very well documented but you can take a look at some example usage in the [rabbitmq-formula](https://github.com/mitodl/rabbitmq-formula)

I'm happy to answer questions on its use and suggestions are welcome :)

**Comment by BadgerOps** [comment]
Awesome, I'll take a look - thanks!

**Pull request merged**
